### ISSUE TITLE
Probar funcionamiento de las máquinas virtuales en local

### ISSUE THREAD

**Issue by jmanday** [jmanday/CRUT#20]

**Comment by mortega87** [comment]
He corregido tu hito y como vemos a continuación todo funciona correctamente.

He ejecutado tu Vagrantfile y como vemos todo se realiza correctamente.

![alt tag](https://rawgit.com/mortega87/Images/master/correccionJesus1.png)

![alt tag](https://rawgit.com/mortega87/Images/master/correccionJesus2.png)

Vemos en la lista de boxes como las tuyas están incluidas.

![alt tag](https://rawgit.com/mortega87/Images/master/correccionJesus3.png)

Vemos como en VirtualBox tambien están incluidas.

![alt tag](https://rawgit.com/mortega87/Images/master/correccionJesus4.png)
